# Generated by Django 4.2.2 on 2024-02-27 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_time', models.DateTimeField()),
                ('personal_id', models.CharField(blank=True, max_length=50, null=True)),
                ('first_name', models.CharField(blank=True, max_length=300, null=True)),
                ('last_name', models.CharField(blank=True, max_length=300, null=True)),
                ('card_number', models.CharField(blank=True, max_length=20, null=True)),
                ('device_name', models.CharField(blank=True, max_length=200, null=True)),
                ('event_point', models.CharField(blank=True, max_length=200, null=True)),
                ('verify_type', models.CharField(blank=True, max_length=100, null=True)),
                ('in_out_status', models.CharField(blank=True, max_length=100, null=True)),
                ('event_description', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
