# Generated by Django 4.2.2 on 2024-03-02 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0002_csv'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='personal_id',
            new_name='personnel_id',
        ),
    ]
