# Generated by Django 4.2.2 on 2024-03-22 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0003_rename_personal_id_history_personnel_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='date_time',
        ),
        migrations.AddField(
            model_name='history',
            name='date',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='history',
            name='time',
            field=models.TimeField(default=None),
        ),
    ]
