# Generated by Django 4.2.2 on 2024-01-29 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('card_number1', models.CharField(max_length=20)),
                ('card_number2', models.CharField(max_length=20)),
                ('card_number3', models.CharField(max_length=20)),
                ('team', models.CharField(choices=[('BFS', 'BFS'), ('DEVS', 'DEVS')], max_length=50)),
            ],
        ),
    ]
