# Generated by Django 4.2.2 on 2024-01-29 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='card_number2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='card_number3',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
