# Generated by Django 4.2.2 on 2024-01-30 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_employee_card_number2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='register_date',
            field=models.DateField(auto_now=True),
        ),
    ]
