# Generated by Django 4.2.2 on 2024-01-31 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_employee_register_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='ace',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
