# Generated by Django 4.2.2 on 2024-02-08 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_employee_ace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='ace',
            field=models.CharField(default='0001', max_length=30),
        ),
    ]
