# Generated by Django 4.2.2 on 2024-03-22 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_leave'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='leave_type',
            field=models.CharField(choices=[('WFH', 'WFH'), ('SL', 'Sick'), ('VL', 'Vacations'), ('BL', 'Bereavement'), ('ML', 'Maternity'), ('PL', 'Paternity'), ('CL', 'Compensatory')], default='VL', max_length=50),
        ),
    ]
