# Generated by Django 4.2.2 on 2024-02-08 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarDay',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField(unique=True)),
                ('team', models.CharField(choices=[('BFS', 'BFS'), ('DEVS', 'DEVS'), ('All', 'All'), ('Optional', 'Optional')], max_length=50)),
            ],
        ),
    ]
